### ISSUE TITLE
Conversion fails with preprocessor error

### ISSUE THREAD

**Issue by pintail-xyz** [klane/jekyllnb#147]
I've got jekyllnb installed in the same virtualenv I use for jupyter notebooks, but when I try to run a conversion I get the error below:

```
(jupyter_env) me@laptop:~/project$ jupyter jekyllnb --site-dir ../site/ --page-dir ../site/_posts/ data_prep.ipynb

Traceback (most recent call last):
  File "/home/me/jupyter_env/lib/python3.8/site-packages/traitlets/traitlets.py", line 535, in get
    value = obj._trait_values[self.name]
KeyError: 'preprocessors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/me/jupyter_env/bin/jupyter-jekyllnb", line 8, in <module>
    sys.exit(JekyllNB.launch_instance())
  File "/home/me/jupyter_env/lib/python3.8/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/me/jupyter_env/lib/python3.8/site-packages/traitlets/config/application.py", line 837, in launch_instance
    app.start()
  File "/home/me/jupyter_env/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 340, in start
    self.convert_notebooks()
  File "/home/me/jupyter_env/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 500, in convert_notebooks
    self.exporter = cls(config=self.config)
  File "/home/me/jupyter_env/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 263, in __init__
    super(TemplateExporter, self).__init__(config=config, **kw)
  File "/home/me/jupyter_env/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 110, in __init__
    self._init_preprocessors()
  File "/home/me/jupyter_env/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 263, in _init_preprocessors
    for preprocessor in self.preprocessors:
  File "/home/me/jupyter_env/lib/python3.8/site-packages/jekyllnb/exporter.py", line 45, in preprocessors
    return super().preprocessors + ["jekyllnb.JekyllPreprocessor"]
  File "/home/me/jupyter_env/lib/python3.8/site-packages/traitlets/traitlets.py", line 575, in __get__
    return self.get(obj, cls)
  File "/home/me/jupyter_env/lib/python3.8/site-packages/traitlets/traitlets.py", line 538, in get
    default = obj.trait_defaults(self.name)
  File "/home/me/jupyter_env/lib/python3.8/site-packages/traitlets/traitlets.py", line 1573, in trait_defaults
    raise TraitError("'%s' is not a trait of '%s' "
traitlets.traitlets.TraitError: 'preprocessors' is not a trait of 'JekyllExporter' instances
```

**Comment by klane** [comment]
Thank you for your interest @pintail-xyz. It looks like there is an updated version of traitlets that satisfies the dependency requirement in the lock file, but introduces a breaking change. What version do you have installed?

**Comment by klane** [comment]
Hi @pintail-xyz, I updated the code to be compatible with the latest versions of nbconvert and traitlets. The latest version of jekyllnb (0.3.1) works on my end. Are you able to confirm this resolves the issue?

**Comment by pintail-xyz** [comment]
Thanks very much, seems to be working fine now.
